### PR TITLE
Add missing dependency: dns-agent

### PR DESCRIPTION
**Pull request by rtorrero**
I tried using the osapi npm module today, found it crashing due to a missing dependency on this module.

### CODE REVIEW

**Comment by rtorrero** [comment]
Just fixed the issue by adding dns-agent to the package.json file.

**Comment by YounGoat** [comment]
@rtorrero Thanks for your commit, I have merged the file package.json and re-publish the package to NPM.

**Comment by YounGoat** [comment]
@rtorrero You are the first user of [osapi](https://www.npmjs.com/package/osapi) as I know. Do you successfully finish your work with osapi now? Any questions are welcome.

**Comment by rtorrero** [comment]
@YounGoat Yes, it's working as expected. I'm using Ceph on a docker to test it and so far it's working perfectly. If everything goes right, we will start using it in production in the next 2 months.
PS: Upgraded to 0.2.0

**Comment by YounGoat** [comment]
@rtorrero The latest version of **osapi** or **ceph** is now 0.3.0 with dependencies upgraded. The document has not been completed. So, if anything confusing, let me know please. You may send me email directly to youngoat@163.com

**Pull request merged**
